# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
- name: Controller reset connection
  listen:
    - "elgeeko1.linux.docker : reset_connection"
  changed_when: false
  ansible.builtin.meta:
    reset_connection
