# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
- name: Install openssh-client
  become: true
  ansible.builtin.package:
    name: openssh-client

- name: Ensure ~/.ssh exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: u=rwx,g=,o=

- name: Stat existing SSH keypair
  register: _ssh_server_keypair
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

- name: Generate SSH keypair
  when: not _ssh_server_keypair.stat.exists
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ ssh_server_user }}@{{ inventory_hostname }}"
    mode: u=rw,g=,o=
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Create controller local folder for public ssh keys
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ playbook_dir ~ '/keys/ssh' }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Controller pull public ssh key {{ ssh_server_user }}-{{ inventory_hostname }}.pub
  ansible.builtin.fetch:
    src: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    dest: "{{ playbook_dir ~ '/keys/ssh' }}/{{ ssh_server_user }}-{{ inventory_hostname }}.pub"
    flat: true
    fail_on_missing: true
