# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
- name: Download Spotify GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    dest: /usr/share/keyrings/spotify.gpg
    mode: u=rw,g=r,o=r

- name: Dearmor Spotify GPG key
  become: true
  ansible.builtin.shell: >
    gpg --dearmor
    --output /etc/apt/keyrings/spotify.gpg
    /usr/share/keyrings/spotify.gpg
  args:
    creates: /etc/apt/keyrings/spotify.gpg

- name: Configure Spotify APT repository
  register: _spotify_repo
  become: true
  ansible.builtin.copy:
    path: /etc/apt/sources.list.d/spotify.list
    content: deb [signed-by=/etc/apt/keyrings/spotify.gpg] https://repository.spotify.com stable non-free
    force: false

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: "{{ _spotify_repo.changed }}"

- name: Install Spotify
  become: true
  ansible.builtin.apt:
    name: spotify-client
