# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
- name: Configure git
  ansible.builtin.import_tasks: git.yml
  
- name: Configure gpg
  when: git_generate_gpg
  ansible.builtin.import_tasks: gpg.yml
