---
- name: Ensure ~/.config/autostart exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    mode: u=rwx,g=rx,o=rx

# drop a user-level override that hides/disables Zoom autostart even if
# /etc/xdg/autostart/Zoom.desktop exists.
- name: Create Zoom autostart user override
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/autostart/Zoom.desktop"
    mode: u=rw,g=r,o=r
    content: |
      [Desktop Entry]
      Type=Application
      Name=Zoom (disabled)
      Exec=zoom --no-silent
      # Prevent GNOME/KDE from autostarting Zoom
      Hidden=true
      NoDisplay=true
      X-GNOME-Autostart-enabled=false

- name: Ensure local applications dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create Zoom desktop shortcut user override
  ansible.builtin.copy:
    src: /usr/share/applications/Zoom.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/Zoom.desktop"
    remote_src: true
    mode: u=rw,g=r,o=r

- name: Add --no-silent to Exec in user desktop shortcut
  register: _zoom_shortcut
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.local/share/applications/Zoom.desktop"
    regexp: '^Exec=(.*\bzoom)(?!.*--no-silent)(.*)$'
    line: 'Exec=\1 --no-silent\2'
    backrefs: true
    mode: u=rw,g=r,o=r

- name: Update desktop database for user applications dir
  when: _zoom_shortcut.changed
  changed_when: true
  ignore_errors: true  # not fatal
  ansible.builtin.command:
    cmd: "update-desktop-database {{ ansible_env.HOME }}/.local/share/applications"
