# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
# remote host target user to use for user-scoped tasks.
terminal_user: "{{ ansible_user
  | default(ansible_ssh_user)
  | default(lookup('ansible.builtin.env', 'USER')) }}"
